UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

## ------------------------- ##
#pagina_ayuda:
#    pattern: /ayuda
#    defaults: { _controller: OfertaBundle:Default:ayuda }

## ------------------------- ##

#pagina_estatica:
#    pattern: /sitio/{pagina}/
#    defaults: { _controller: OfertaBundle:Sitio:estatica }

## ------------------------- ##

#pagina_estatica:
#    pattern : /sitio/{pagina}
#    defaults: { _controller: OfertaBundle:Sitio:estatica }

#_pagina_estatica:
#    pattern : /sitio/{pagina}/
#    defaults: { _controller: OfertaBundle:Sitio:estatica }

## ------------------------- ##

pagina_estatica:
    pattern : /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

_pagina_estatica:
    pattern : /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: pagina_estatica }

# _controller: bubdle:controlador:accion

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
